### ISSUE TITLE
Cargo unit cap

### ISSUE THREAD

**Issue by Brandanvimi** [xjamiex/BioTech#4]
When the carrier unit cap is reached, the game disables you from placing any new unit dockers.
![image](https://github.com/xjamiex/BioTech/assets/157245702/d2a48b7f-af36-4f92-b0b5-ef2c81d6203b)

***But*** if you had them placed down before the cap was reached (by placing one down during the creation of the last carrier) the unit dockers will stop producing the carriers that would break the cap. While they stop making new units, their animation also stops.
![unit docker stoped](https://github.com/xjamiex/BioTech/assets/157245702/f6b941b6-86d2-44de-bc53-da834b3578b7)

**Comment by xjamiex** [comment]
That is intentional, maybe I will remove the cap later, but for now, that is meant to happen

**Comment by Brandanvimi** [comment]
I forgot to close this, oops
